/* eslint-disable import/prefer-default-export, @typescript-eslint/camelcase */

export const addMovieByImdbId = {
  movie: {
    status: 'active',
    info: {
      rating: {
        imdb: [0, 0],
      },
      genres: ['Adventure', 'Fantasy', 'Music', 'Romance', 'Comedy', 'Family', 'Musical'],
      tmdb_id: 420817,
      plot: 'A live-action retelling of the 1992 Disney film of the same name.',
      tagline: 'Choose Wisely.',
      original_title: 'Aladdin',
      actor_roles: {
        'Nasim Pedrad': 'Dalia',
        'Navid Negahban': 'The Sultan',
        'Marwan Kenzari': 'Jafar',
        'Will Smith': 'Genie',
        'Frank Welker': 'Abu (voice) / The Cave of Wonders (voice)',
        'Naomi Scott': 'Jasmine',
        'Robby Haynes': 'Razoul',
        'Alan Tudyk': 'Iago',
        'Mena Massoud': 'Aladdin',
        'Billy Magnussen': 'Prince Anders',
        'Numan Acar': 'Hakim',
      },
      via_imdb: true,
      mpaa: null,
      via_tmdb: true,
      directors: ['Guy Ritchie'],
      titles: ['Aladdin', '알라딘', 'Αλαντίν (2019)'],
      imdb: 'tt6139732',
      year: 2019,
      images: {
        disc_art: [],
        poster: ['https://image.tmdb.org/t/p/w154/uF3zJmoYQUab5tiUfUECKpkkjIJ.jpg', 'https://m.media-amazon.com/images/M/MV5BMjQ2ODIyMjY4MF5BMl5BanBnXkFtZTgwNzY4ODI2NzM@._V1_SX300.jpg'],
        extra_thumbs: [],
        poster_original: ['https://image.tmdb.org/t/p/original/uF3zJmoYQUab5tiUfUECKpkkjIJ.jpg'],
        landscape: [],
        actors: {
          'Nasim Pedrad': 'https://image.tmdb.org/t/p/w185/kA12uJDhiLW6xhTYJEwhMFjJBjb.jpg',
          'Navid Negahban': 'https://image.tmdb.org/t/p/w185/qxp9X0SIA0FWts2qK60IcrmUhnF.jpg',
          'Will Smith': 'https://image.tmdb.org/t/p/w185/eze9FO9VuryXLP0aF2cRqPCcibN.jpg',
          'Frank Welker': 'https://image.tmdb.org/t/p/w185/b3gImArbw13mMKJIe9leFc9YYb7.jpg',
          'Naomi Scott': 'https://image.tmdb.org/t/p/w185/d140yTWCle6rYUGE9GIVZVPaPng.jpg',
          'Marwan Kenzari': 'https://image.tmdb.org/t/p/w185/k0qx65csI86rAFBR4Sal7phY3Vl.jpg',
          'Alan Tudyk': 'https://image.tmdb.org/t/p/w185/6QuMtbD8kmhpwWhFKfNzEvHRLOu.jpg',
          'Mena Massoud': 'https://image.tmdb.org/t/p/w185/ydgJOEIUlCNoqYkTNm7PWzoFUoU.jpg',
          'Billy Magnussen': 'https://image.tmdb.org/t/p/w185/beXgMEBhkWS8BUsc69ojIOGiakV.jpg',
          'Numan Acar': 'https://image.tmdb.org/t/p/w185/cJ0wLZDcyFKbRslfVNtiyl3XJqC.jpg',
        },
        backdrop_original: ['https://image.tmdb.org/t/p/original/vjHArnGFarPCfpMsLA1JEZsCd8O.jpg'],
        clear_art: [],
        logo: [],
        banner: [],
        backdrop: ['https://image.tmdb.org/t/p/w1280/vjHArnGFarPCfpMsLA1JEZsCd8O.jpg'],
        extra_fanart: [],
      },
      actors: ['Naomi Scott', 'Mena Massoud', 'Will Smith', 'Marwan Kenzari'],
      writers: ['John August (screenplay by)', 'Guy Ritchie (screenplay by)'],
      runtime: 0,
      type: 'movie',
      released: '2019-05-22',
    },
    _t: 'media',
    releases: [],
    tags: [],
    _rev: '00069711',
    profile_id: 'f8e09d9a2657477b8b2373c54db272e1',
    _id: 'b31d085ce72e4aec88c6a2f4502d1de2',
    title: 'Aladdin',
    last_edit: 1553337471,
    category_id: null,
    type: 'movie',
    files: {
      image_poster: ['/var/opt/couchpotato/cache/6d742742819ae41c5468e0c6e5870fac.jpg'],
    },
    identifiers: {
      imdb: 'tt6139732',
    },
  },
  success: true,
};
